os:
    - linux
    - osx
language: generic
sudo: required
dist: trusty

osx_image: xcode11.5
before_install:
    - if [ $TRAVIS_OS_NAME == "osx" ]; then
            brew install caskroom/cask/vapor;
            brew tap vapor/tap;
            brew update;
            brew install vapor;
        else
            eval "$(curl -sL https://swiftenv.fuller.li/install.sh)";
            eval "$(curl -sL https://apt.vapor.sh)";
            sudo apt-get install vapor;
            sudo chmod -R a+rx /usr/;
        fi

script:
    - swift --version
    - swift build
    - swift build -c release
    - swift test

after_success:
    - bash <(curl -s https://codecov.io/bash)
